### PR TITLE
DEV-15174 - feat: add variable for specifying TAMR_DATASET_EMR_CLUSTER_NAME_PREFIX

### PR DESCRIPTION
**Pull request by skalish**

### CODE REVIEW

**Review by souza-dan — COMMENTED** [review]
Changes look good! Just update the CHANELOG and VERSION files.

Seems like a minor version to me.

**Review by souza-dan — APPROVED** [review]

**Comment by skalish** [comment]
Actually, is it correct that this config should be added to `tamr-config.yml` or should instead be in `ephemeral-spark-config.tf`. I'm confused as to what the difference is between these.

**Comment by skalish** [comment]
> Actually, is it correct that this config should be added to `tamr-config.yml` or should instead be in `ephemeral-spark-config.tf`. I'm confused as to what the difference is between these.

I see now that the latter are only set if ephemeral spark is configured.  In this case (as well as an upcoming addition of emr_security_configuration) I think these variable do only get used when the Spark cluster is ephemeral.  Let me know if I've got this wrong.

**Comment by skalish** [comment]
@souza-dan I also moved the emr-cluster-tags variable.  Let me know if that was too aggressive and I can rollback that commit before merging.

**Pull request merged**
