### PR TITLE
SUP-5438 Optionally copy config to s3

### PR DESCRIPTION
**Pull request by along528**

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by souza-dan — COMMENTED** [review]
You'll need to bump the minor version since we're adding a feature and update the changelog.

You'll also want to update the example, that already did this.
https://github.com/Datatamer/terraform-aws-tamr-config/blob/d8ec030002f13d6777ab5cc3c03b4017feb28f5e/examples/ephemeral-spark/tamr-config.tf#L62-L68

If it's very common, sure we can add that.

The composability of the module already allows you to choose what you want to do with output.

**Comment by rubab2** [comment]
@along528 This has been possible for some time already, I think? For example, the block following this:
https://github.com/Datatamer/customers-abbvie-deployment/blob/pre-deploy-V2.5/workspace/tamr-config.tf#L55

**Comment by along528** [comment]
@rubab2 @along528 Indeed I agree this is unnecessary. Closing

**Pull request closed without merging**
