### PR TITLE
DEV-14662 - bugfix for conflating TAMR_JOB_SPARK_PROPS and TAMR_JOB_SPARK_CONFIG_OVERRIDES

### PR DESCRIPTION
**Pull request by clint-richardson**
fixes bug found here: https://tamr.slack.com/archives/CT6SG4L2X/p1613611012021100

by separating out the two and adding working defaults for each.

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by daniosim — APPROVED** [review]
Nice, thanks for fixing. Could you bump the [version](https://github.com/Datatamer/terraform-aws-tamr-config/blob/master/VERSION) and add a small comment in the [changelog](https://github.com/Datatamer/terraform-aws-tamr-config/blob/master/CHANGELOG.md) so we can tag a new release? Otherwise looks good 👍

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by clint-richardson** [comment]
@daniosim I took a stab at this. Let me know if I'm following your preferred convention/language correctly

**Comment by daniosim** [comment]
> @daniosim I took a stab at this. Let me know if I'm following your preferred convention/language correctly

Yep, looks great. I forgot to mention earlier, might also be helpful to change bump the version in the commented source in the example: https://github.com/Datatamer/terraform-aws-tamr-config/blob/master/examples/ephemeral-spark/tamr-config.tf#L2

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by clint-richardson** [comment]
thanks for that call out - I updated both example files. Let me know if there is anything else

**Comment by daniosim** [comment]
Can't think of anything else, looks good to merge 👍

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by souza-dan — APPROVED** [review]
LGTM 

made you a ticket:
https://datatamr.atlassian.net/browse/DEV-14662

**Pull request merged**
