### PR TITLE
SUP-5367 Add HBase SHARED mode to default Tamr config

### PR DESCRIPTION
**Pull request by olivito**

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by olivito** [comment]
@souza-dan I noticed that the AWS config explicitly sets 
```
TAMR_HBASE_SORT_BATCHES_ENABLED: false
```
is there a reason for this?

**Comment by souza-dan** [comment]
> @souza-dan I noticed that the AWS config explicitly sets
> 
> ```
> TAMR_HBASE_SORT_BATCHES_ENABLED: false
> ```
> 
> is there a reason for this?

Not that I know of, let's change it.

**Comment by olivito** [comment]
> > @souza-dan I noticed that the AWS config explicitly sets
> > ```
> > TAMR_HBASE_SORT_BATCHES_ENABLED: false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is there a reason for this?
> 
> Not that I know of, let's change it.

I'll check on the scale channel to be sure before changing it.

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by olivito** [comment]
> > > @souza-dan I noticed that the AWS config explicitly sets
> > > ```
> > > TAMR_HBASE_SORT_BATCHES_ENABLED: false
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > is there a reason for this?
> > 
> > 
> > Not that I know of, let's change it.
> 
> I'll check on the scale channel to be sure before changing it.

@souza-dan I've removed this line to use the Tamr-default of `true`, to be consistent with the Azure config module and following the discussion on the scale channel:
https://tamr.slack.com/archives/CT6SG4L2X/p1625256592127000

Let me know if you'd prefer to explicitly set `TAMR_HBASE_SORT_BATCHES_ENABLED` and `TAMR_HBASE_SORT_BATCHES_BUFFER_FACTOR` explicitly in this config module.

**Review by souza-dan — APPROVED** [review]
LGTM

**Pull request merged**
